# Generated by Django 2.1.7 on 2019-04-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
