# Generated by Django 2.1.7 on 2019-04-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190406_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('clg_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('clg_name', models.CharField(max_length=100)),
            ],
        ),
    ]
